In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns


In [2]:
from sklearn.datasets import make_classification
x,y= make_classification(
    n_classes=2,
    n_features=3,
    n_redundant=1,
    n_samples=1000,
    random_state=23
)

In [3]:
x


array([[-1.4790621 , -0.12039883, -0.67728607],
       [ 1.43386725,  0.06628378,  0.87298889],
       [-1.03154736, -0.49636711,  1.29704504],
       ...,
       [ 0.14605733,  0.43100152, -1.73133689],
       [-0.72937064, -0.36396875,  0.97289371],
       [ 0.91319159,  0.13280516,  0.16729944]])

In [4]:
from sklearn.model_selection import train_test_split


In [5]:
x_train,x_test,y_train,y_test=train_test_split(x,y ,test_size=0.30 ,random_state=93)

In [6]:
x_train

array([[ 0.65950488,  0.04944433,  0.32019305],
       [ 1.15153624,  0.57534455, -1.53904909],
       [ 0.11518985,  0.01863238,  0.01303538],
       ...,
       [ 0.68602284,  0.46806706, -1.45452135],
       [-0.69111428, -0.3146782 ,  0.79229008],
       [-1.6195623 , -0.62534989,  1.37582009]])

In [7]:
from sklearn.neighbors import KNeighborsClassifier

In [8]:
classifier=KNeighborsClassifier(n_jobs=5,algorithm='auto')
classifier.fit(x_train,y_train)

KNeighborsClassifier(n_jobs=5)

In [9]:
y_pred=classifier.predict(x_test)

In [11]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [12]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[145  15]
 [ 14 126]]
0.9033333333333333
              precision    recall  f1-score   support

           0       0.91      0.91      0.91       160
           1       0.89      0.90      0.90       140

    accuracy                           0.90       300
   macro avg       0.90      0.90      0.90       300
weighted avg       0.90      0.90      0.90       300



In [13]:
from sklearn.model_selection import GridSearchCV

In [15]:
param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11, 13, 15],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan']
}

In [16]:
grid = GridSearchCV(
    estimator=classifier,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_jobs=5), n_jobs=-1,
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 9, 11, 13, 15],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [17]:
print("Best Parameters:")
print(grid.best_params_)

Best Parameters:
{'metric': 'manhattan', 'n_neighbors': 9, 'weights': 'uniform'}


In [18]:
best_knn = grid.best_estimator_

In [19]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nTest Accuracy:")
print(accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[145  14]
 [ 15 126]]

Test Accuracy:
0.9033333333333333

Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.91      0.91       159
           1       0.90      0.89      0.90       141

    accuracy                           0.90       300
   macro avg       0.90      0.90      0.90       300
weighted avg       0.90      0.90      0.90       300



In [20]:
results = pd.DataFrame(grid.cv_results_)

results[
    [
        'param_n_neighbors',
        'param_weights',
        'param_metric',
        'mean_test_score',
        'rank_test_score'
    ]
].sort_values('rank_test_score')

,param_n_neighbors,param_weights,param_metric,mean_test_score,rank_test_score
20,9,uniform,manhattan,0.937143,1
22,11,uniform,manhattan,0.935714,2
8,11,uniform,euclidean,0.934286,3
4,7,uniform,euclidean,0.931429,4
21,9,distance,manhattan,0.931429,4
23,11,distance,manhattan,0.931429,4
9,11,distance,euclidean,0.931429,4
13,15,distance,euclidean,0.931429,4
24,13,uniform,manhattan,0.931429,4
10,13,uniform,euclidean,0.930000,10
